name: deepcare
description: "DeepCare Clock - A personalized digital clock app."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI
  lucide_icons_flutter: ^3.0.5
  flex_color_picker: ^3.7.1
  lottie: ^3.3.1

  # State Management
  flutter_riverpod: ^2.4.0
  riverpod_annotation: ^2.4.0

  # HTTP
  dio: ^5.8.0+1

  # Models
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0

  # Utils
  intl: ^0.20.2
  build_runner: ^2.5.3
  shared_preferences: ^2.5.3
  collection: ^1.19.1
  timeago: ^3.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  # Code Generation
  freezed: ^2.4.1
  riverpod_generator: ^2.4.0
  json_serializable: ^6.9.5

  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/clock.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  background_color: "#FFFFFF"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/clock.png"

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/animations/

  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi-Light.otf
          weight: 300
        - asset: assets/fonts/Satoshi-Regular.otf
          weight: 400
        - asset: assets/fonts/Satoshi-Medium.otf
          weight: 500
        - asset: assets/fonts/Satoshi-Bold.otf
          weight: 700
        - asset: assets/fonts/Satoshi-Black.otf
          weight: 900
